

const cardData = [

    {
        id: "301",
        title: "Face Wash",
        description: "Gentle face wash designed for acne-prone and sensitive skin.",
        image: "https://th.bing.com/th/id/OIP.a4YJkAFE0kaztat1BTmL9QHaF8?rs=1&pid=ImgDetMain",
        price: "₹250",
        oldPrice: "₹299",
        quantity: "100 ml",
        ingredients: "Salicylic Acid, Tea Tree Oil",
        usageInstructions: "Use twice daily on wet face, gently massage and rinse.",
        warranty: "Not applicable",
        certifications: "Dermatologically Tested",
        skinType: "All Skin Types",
        hypoallergenic: "Yes",
        waterproof: "No",
        category: "Personal Care"
      },
      {
        id: "302",
        title: "Body Lotion",
        description: "Long-lasting hydration with a non-greasy formula.",
        image: "https://myforeverwellness.com/wp-content/uploads/2021/01/BeFunky-design-66-scaled.jpg",
        price: "₹180",
        oldPrice: "₹210",
        quantity: "200 ml",
        ingredients: "Aloe Vera, Vitamin E",
        usageInstructions: "Apply generously after bath or as needed.",
        warranty: "Not applicable",
        certifications: "ISO 9001 Certified",
        skinType: "Dry to Normal Skin",
        hypoallergenic: "Yes",
        waterproof: "No",
        category: "Personal Care"
      },
      {
        id: "303",
        title: "Hair Oil",
        description: "Nourishing hair oil for hair fall control and healthy scalp.",
        image: "https://th.bing.com/th/id/OIP.vuww8AxKV7ot4g6TUCuulwHaHa?rs=1&pid=ImgDetMain",
        price: "₹160",
        oldPrice: "₹185",
        quantity: "200 ml",
        ingredients: "Bhringraj, Amla, Coconut Oil",
        usageInstructions: "Massage gently on scalp 2-3 times a week.",
        warranty: "Not applicable",
        certifications: "Ayurvedic Proprietary Medicine",
        skinType: "All Hair Types",
        hypoallergenic: "Yes",
        waterproof: "No",
        category: "Personal Care"
      },
      {
        id: "304",
        title: "Anti-Dandruff Shampoo",
        description: "Effective solution for dandruff and scalp itchiness.",
        image: "https://i5.walmartimages.com/seo/Anti-Dandruff-Hydrating-Shampoo_5383b5f2-3cf9-4d5e-9525-adf8dbf3806c.86ea2ffd4ca45814911abe26951e7258.jpeg",
        price: "₹210",
        oldPrice: "₹250",
        quantity: "180 ml",
        ingredients: "Zinc Pyrithione, Aloe Vera",
        usageInstructions: "Use twice a week. Massage on scalp and rinse.",
        warranty: "Not applicable",
        certifications: "Dermatologically Approved",
        skinType: "Scalp Care",
        hypoallergenic: "Yes",
        waterproof: "No",
        category: "Personal Care"
      },
      {
        id: "305",
        title: "Sanitary Pads",
        description: "Ultra-thin sanitary pads with advanced absorbency.",
        image: "https://cdn01.pharmeasy.in/dam/products_otc/E35929/stayfree-secure-ultra-thin-size-xl-sanitary-pads-pack-of-10-2-1600172100.jpg",
        price: "₹95",
        oldPrice: "₹110",
        quantity: "10 Pads",
        ingredients: "Cotton, Absorbent Gel Core",
        usageInstructions: "Change every 4-6 hours.",
        warranty: "Not applicable",
        certifications: "ISO 13485, CE",
        hypoallergenic: "Yes",
        waterproof: "Yes",
        category: "Personal Care"
      },
      {
        id: "306",
        title: "Lip Balm",
        description: "Nourishing lip balm that heals chapped lips and retains moisture.",
        image: "https://media1.popsugar-assets.com/files/thumbor/2cvXVdaRNijrphmoJO3N9Q7AY7I/fit-in/1024x1024/filters:format_auto-!!-:strip_icc-!!-/2020/05/27/753/n/1922153/edb771ebeef09ec5_netimgtZFkbd/i/Laneige-Lip-Glowy-Balm.jpg",
        price: "₹70",
        oldPrice: "₹85",
        quantity: "5 g",
        ingredients: "Beeswax, Shea Butter, Vitamin E",
        usageInstructions: "Apply to lips as needed.",
        warranty: "Not applicable",
        certifications: "FDA Approved",
        skinType: "All Skin Types",
        hypoallergenic: "Yes",
        waterproof: "No",
        category: "Personal Care"
      },
      {
        id: "307",
        title: "Deodorant Roll-On",
        description: "Stay fresh all day with long-lasting odor protection.",
        image: "https://api.watsons.com.ph/medias/zoom-back-10076601.jpg?context=bWFzdGVyfGltYWdlc3wxMDE2MjA0fGltYWdlL2pwZWd8aDM2L2g5Ni84ODg2NTg4MjQzOTk4L1dUQ1BILTEwMDc2NjAxLWJhY2suanBnfGEwNWMzZjBlZTM5NmI3ZDFlM2M1MWFiNzRiNTFkZDM3NzM4NmNjNWVjOTQ1ZWQzYzg1MzU1MGYzMTY5MTIzMzM",
        price: "₹120",
        oldPrice: "₹145",
        quantity: "50 ml",
        ingredients: "Alum, Fragrance, Aqua",
        usageInstructions: "Apply on clean underarms. Avoid broken skin.",
        warranty: "Not applicable",
        certifications: "Dermatologically Tested",
        skinType: "All Skin Types",
        hypoallergenic: "Yes",
        waterproof: "No",
        category: "Personal Care"
      },
      {
        id: "308",
        title: "Hand Cream",
        description: "Hydrates and softens rough hands, perfect for daily use.",
        image: "https://i5.walmartimages.com/asr/5a2551ef-d8b5-4cce-aa62-a709a7c69143.c8b715e5ba1cd5d239892359469b6a4e.jpeg",
        price: "₹140",
        oldPrice: "₹160",
        quantity: "75 ml",
        ingredients: "Shea Butter, Glycerin, Vitamin E",
        usageInstructions: "Massage onto hands until fully absorbed.",
        warranty: "Not applicable",
        certifications: "ISO 22716 Certified",
        skinType: "Dry to Normal",
        hypoallergenic: "Yes",
        waterproof: "No",
        category: "Personal Care"
      }
];

export default cardData;
